#! /bin/sh

#single display
#bspc monitor -d I II III IV V VI VII VIII IX X

#multiple displays
bspc monitor HDMI1 -d 1 3 5 7 9
bspc monitor HDMI2 -d 2 4 6 8 10

bspc config border_width         2
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled

bspc config active_border_color '#0C1115'
bspc config normal_border_color '#0C1115'
bspc config focused_border_color '#F1F1F1'

#since sxhkd ceased work with lightdm until killed and restarted,
#theese two lines were added
pkill sxhkd
sxhkd &

#for multiple displays
xrandr --output HDMI1 --auto --left-of HDMI2

xsetroot -cursor_name left_ptr
#xsetroot -solid "#BE616B"
setxkbmap -option grp:alt_space_toggle us,ru &

# --no-xinerama allows to strech wallp on dual monotor set
feh --bg-fill --no-xinerama ~/pix/wlp/gray-scale-photo-of-body-of-water-194735.jpg
#feh --bg-scale --no-xinerama ~/pix/wlp/jacky-zeng-tqsfdwxRyq4-unsplash.jpg

#These two lines should be at the bottom to work properly with two displays
#TODO replace with lemonbar
$HOME/.config/polybar/launch.sh
