#! /bin/sh

#sxhkd &

#TODO replace with lemonbar
$HOME/.config/polybar/launch.sh


#single display
#bspc monitor -d I II III IV V VI VII VIII IX X

#multiple displays
bspc monitor HDMI1 -d I III V VII IX
bspc monitor HDMI2 -d II IV VI VIII X

bspc config border_width         2
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled

bspc config active_border_color '#0C1115'
bspc config normal_border_color '#0C1115'
bspc config focused_border_color '#F1F1F1'

#for multiple displays
xrandr --output HDMI1 --auto --left-of HDMI2

xsetroot -cursor_name left_ptr
xsetroot -solid "#BE616B"
setxkbmap -option grp:alt_space_toggle us,ru &
